title: Art, History, Religion, and Philosophy
email: author@goodlifeodyssey.com
description: Essays and notes about literature, history, religion, and philosophy.
baseurl: ""
url: "http://goodlifeodyssey.com"

markdown: kramdown
theme: minima
config:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - sitemap.txt
collections:
  published:
    output: true
    permalink: /:path
defaults:
  - scope:
      path: ""
    values:
      layout: basic
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
