name: Pull From Notion
on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 * * * *' # run at 2 AM UTC
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.16.2/pandoc-2.16.2-1-amd64.deb
          sudo dpkg -i pandoc-2.16.2-1-amd64.deb
          sudo apt-get install -f
          rm -rf pandoc-2.16.2-1-amd64.deb
          sudo apt-get install nodejs npm libpng-dev
          npm install -g @mermaid-js/mermaid-cli
          npm install
          python -m pip install --upgrade pip setuptools
          rm -rf src/n2y
          pip install -r requirements.txt
      - name: Generate pages
        env:
          NOTION_ACCESS_TOKEN: ${{ secrets.NOTION_ACCESS_TOKEN }}
          PYTHONPATH: "."
        run: make cleannotion && make notion && make -j4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Nightly release
          title: Nightly release
          body: Nightly release
          branch: nightly-release
          base: main
